from state_representation import SRLType
from environments.kuka_gym.kuka_button_gym_env import KukaButtonGymEnv

# format NAME: (SRLType, LIMITED_TO_ENV)
registered_srl = {
    "raw_pixels": (SRLType.ENVIRONMENT, None),
    "ground_truth": (SRLType.ENVIRONMENT, None),
    "joints": (SRLType.ENVIRONMENT, [KukaButtonGymEnv]),
    "joints_position": (SRLType.ENVIRONMENT, [KukaButtonGymEnv]),
    "robotic_priors": (SRLType.SRL, None),
    "inverse": (SRLType.SRL, None),
    "forward": (SRLType.SRL, None),
    "multi_view_srl": (SRLType.SRL, None),
    "srl_combination": (SRLType.SRL, None),
    "supervised": (SRLType.SRL, None),
    "autoencoder": (SRLType.SRL, None),
    "autoencoder_inverse": (SRLType.SRL, None),
    "autoencoder_reward": (SRLType.SRL, None),
    "autoencoder_forward": (SRLType.SRL, None),
    "random": (SRLType.SRL, None),
    "random_inverse": (SRLType.SRL, None),
    "reward_inverse": (SRLType.SRL, None),
    "srl_splits": (SRLType.SRL, None),
    "srl_split_forward": (SRLType.SRL, None),
    "srl_3_splits": (SRLType.SRL, None),
    "reward": (SRLType.SRL, None),
    "vae": (SRLType.SRL, None),
    "dae": (SRLType.SRL, None),
    "pca": (SRLType.SRL, None),
    "gan": (SRLType.SRL, None),
    "unet": (SRLType.SRL, None),
    "gan_inverse": (SRLType.SRL, None),
    "gan_forward": (SRLType.SRL, None),
    "gan_reward": (SRLType.SRL, None),
    "gan_inverse_reward": (SRLType.SRL, None),
    "gan_inverse_forward": (SRLType.SRL, None),
    "gan_forward_reward": (SRLType.SRL, None),
    "AE_forward_reward": (SRLType.SRL, None),
    "AE_inverse_forward": (SRLType.SRL, None),
    "AE_inverse_reward":  (SRLType.SRL, None),
    "AE_inv_rwd_split": (SRLType.SRL, None),
    "srl_split_all": (SRLType.SRL, None),
    "srl_split_ir": (SRLType.SRL, None),
    "srl_split_ir2": (SRLType.SRL, None),
    "srl_split_ir3": (SRLType.SRL, None),
    "srl_split_ir4": (SRLType.SRL, None),
    "srl_split_fr1": (SRLType.SRL, None),
    "srl_split_ir_new": (SRLType.SRL, None),
    "srl_split_ifr_new2": (SRLType.SRL, None),
    "srl_split_ifr_new2_200": (SRLType.SRL, None),
}
